name: Deploy Fake
on:
    workflow_call:
jobs:
    deploy_kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando deploy no ambiente de ${{ secrets.AMBIENTE_ENTREGA }}"
